Testing on unit 01
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 350, in __call__
    return self.func(*args, **kwargs)
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/njw275/NJW-BirdVox/src/python_files/GetF.py", line 23, in get_F
    num_onsets += co.counting_onsets(unit, start_time)
NameError: name 'co' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 359, in __call__
    raise TransportableException(text, e_type)
joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
NameError                                          Thu Jun 29 15:14:17 2017
PID: 28287      Python 3.6.1: /home/njw275/miniconda3/envs/birds/bin/python
...........................................................................
/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function get_F>, ([2], 0.0), {})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function get_F>
        args = ([2], 0.0)
        kwargs = {}
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/njw275/NJW-BirdVox/src/python_files/GetF.py in get_F(training_set=[2], threshold=0.0)
     18         start_times = st.get_start_time(unit)
     19         for start_time in start_times:
     20 
     21             Tp, Fp, Fn = det.threshold(unit, start_time, threshold)
     22 #           find LOCAL num_onsets, true_pos, false_neg, false_pos
---> 23             num_onsets += co.counting_onsets(unit, start_time)
        num_onsets = 0
        unit = 2
        start_time = '23395'
     24             true_pos += Tp
     25             false_neg += Fn
     26             false_pos += Fp
     27     if (true_pos + false_pos) == 0:

NameError: name 'co' is not defined
___________________________________________________________________________
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
NameError                                          Thu Jun 29 15:14:17 2017
PID: 28287      Python 3.6.1: /home/njw275/miniconda3/envs/birds/bin/python
...........................................................................
/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function get_F>, ([2], 0.0), {})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function get_F>
        args = ([2], 0.0)
        kwargs = {}
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/njw275/NJW-BirdVox/src/python_files/GetF.py in get_F(training_set=[2], threshold=0.0)
     18         start_times = st.get_start_time(unit)
     19         for start_time in start_times:
     20 
     21             Tp, Fp, Fn = det.threshold(unit, start_time, threshold)
     22 #           find LOCAL num_onsets, true_pos, false_neg, false_pos
---> 23             num_onsets += co.counting_onsets(unit, start_time)
        num_onsets = 0
        unit = 2
        start_time = '23395'
     24             true_pos += Tp
     25             false_neg += Fn
     26             false_pos += Fp
     27     if (true_pos + false_pos) == 0:

NameError: name 'co' is not defined
___________________________________________________________________________

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SplittingandEvaluating.py", line 54, in <module>
    threshold_Fs = Parallel(n_jobs=-1)(delayed(gf.get_F)(training_set, th) for th in thresholds)
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py", line 740, in retrieve
    raise exception
joblib.my_exceptions.JoblibNameError: JoblibNameError
___________________________________________________________________________
Multiprocessing exception:
...........................................................................
/home/njw275/NJW-BirdVox/src/python_files/SplittingandEvaluating.py in <module>()
     49 for split_id in range(len(units)):
     50     test_set, training_set = sp.split_units(split_id) 
     51     #training_set.pop(training_set.index(10))
     52     print("Testing on unit " + str(test_set[0]).zfill(2))
     53     
---> 54     threshold_Fs = Parallel(n_jobs=-1)(delayed(gf.get_F)(training_set, th) for th in thresholds)
     55         
     56     # find best threshold (argmax) and print it to slurm
     57     best_threshold_id = np.argmax(threshold_Fs)
     58     best_threshold = thresholds[best_threshold_id]

...........................................................................
/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=-1), iterable=<generator object <genexpr>>)
    784             if pre_dispatch == "all" or n_jobs == 1:
    785                 # The iterable was consumed all at once by the above for loop.
    786                 # No need to wait for async callbacks to trigger to
    787                 # consumption.
    788                 self._iterating = False
--> 789             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=-1)>
    790             # Make sure that we get a last message telling us we are done
    791             elapsed_time = time.time() - self._start_time
    792             self._print('Done %3i out of %3i | elapsed: %s finished',
    793                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Sub-process traceback:
---------------------------------------------------------------------------
NameError                                          Thu Jun 29 15:14:17 2017
PID: 28287      Python 3.6.1: /home/njw275/miniconda3/envs/birds/bin/python
...........................................................................
/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function get_F>, ([2], 0.0), {})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/njw275/miniconda3/envs/birds/lib/python3.6/site-packages/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function get_F>
        args = ([2], 0.0)
        kwargs = {}
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/njw275/NJW-BirdVox/src/python_files/GetF.py in get_F(training_set=[2], threshold=0.0)
     18         start_times = st.get_start_time(unit)
     19         for start_time in start_times:
     20 
     21             Tp, Fp, Fn = det.threshold(unit, start_time, threshold)
     22 #           find LOCAL num_onsets, true_pos, false_neg, false_pos
---> 23             num_onsets += co.counting_onsets(unit, start_time)
        num_onsets = 0
        unit = 2
        start_time = '23395'
     24             true_pos += Tp
     25             false_neg += Fn
     26             false_pos += Fp
     27     if (true_pos + false_pos) == 0:

NameError: name 'co' is not defined
___________________________________________________________________________
